### ISSUE TITLE
Plotting fails on ROCs for large data sets

### ISSUE THREAD

**Issue by jerheff** [erikpeter/fbroc#1] opened 2015-07-20 23:56 UTC
I have a data set with ~2.7 million entries heavily skewed toward negative samples.  I made a boot.roc object via this call:

boot.roc(data$prediction, data$actual, n.boot=1000, use.cache = TRUE)

Calling plot on the object then fails with this error immediately:

plot(bootrocobject, show.metric="auc")
Error in .Call("fbroc_tpr_at_fpr_cached", PACKAGE = "fbroc", tpr, fpr,  : 
  negative length vectors are not allowed

I then tried a small number of bootstrap samples (100), which does not provide an error message, but appears to hang.

**Comment by erikpeter** [comment] 2015-07-23 16:15
Thank you for the report. Unfortunately (or fortunately for me) I am in the first week of a three week vacation. I suspect I won't get to work for it before the second half of August.

Some questions:
- Which version are you using (R and fbroc)?
- What happens in uncached mode? It is more easy on the memory, so it might help

Is the data set confidential or can you share it? If it is confidential I still would like to know:
- How many positive and negative samples?
- Are there ties in the data? If so, how many?
- What AUC do you get?

**Comment by erikpeter** [comment] 2015-09-28 19:08
Now fixed on github. Was caused by a stupid default for the number of points at which the ROC curve was calculated. Should also increase performance when plotting.

Until a new version is on CRAN (a while yet) either use the newest version from Github or switch the positive and negative class as a workaround.

**Closed as completed by erikpeter** 2015-09-28 19:08 UTC
Labels: bug
